### ISSUE TITLE
TendaM3固件binwalk失败

### ISSUE THREAD

**Issue by nyzer0ne** [d1tto/IoT-vuln#1]
您好, 我想复现下TendaM3的相关漏洞, 使用binwalk分离固件后, webroot_ro只分离出了少数文件, 大部分文件被识别为了zlib数据块, 请问您遇到这种问题了吗? 应该如何解决? 或者您是如何成功模拟TendaM3? 非常感谢
![image](https://user-images.githubusercontent.com/111333716/185363391-ef4db4c3-5c54-418c-91c1-f757c6b947ec.png)

**Comment by xywang18** [comment]
1. 漏洞位于/bin目录下的httpd，我应该没有用到webroot
2. 关于模拟执行，我是使用qemu的用户态模拟，模拟之前对httpd进行了patch，[这里有提到](https://github.com/d1tto/IoT-vuln/tree/main/Tenda/M3/fromDhcpListClient)

**Comment by nyzer0ne** [comment]
感谢, 已经可以成功模拟
